'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type FieldMeta, type WbCanvasCustomEvent, type WbFormRendererCustomEvent, type WbInspectorCustomEvent, type WbPaletteCustomEvent } from "@webmobix/form-components";
import type { Components } from "@webmobix/form-components/dist/components";
import { WbCanvas as WbCanvasElement, defineCustomElement as defineWbCanvas } from "@webmobix/form-components/dist/components/wb-canvas.js";
import { WbFormField as WbFormFieldElement, defineCustomElement as defineWbFormField } from "@webmobix/form-components/dist/components/wb-form-field.js";
import { WbFormRenderer as WbFormRendererElement, defineCustomElement as defineWbFormRenderer } from "@webmobix/form-components/dist/components/wb-form-renderer.js";
import { WbInspector as WbInspectorElement, defineCustomElement as defineWbInspector } from "@webmobix/form-components/dist/components/wb-inspector.js";
import { WbPalette as WbPaletteElement, defineCustomElement as defineWbPalette } from "@webmobix/form-components/dist/components/wb-palette.js";

export type WbCanvasEvents = {
    onWbChange: EventName<WbCanvasCustomEvent<FieldMeta[]>>,
    onWbFieldSelected: EventName<WbCanvasCustomEvent<FieldMeta>>,
    onWbFieldDeselected: EventName<WbCanvasCustomEvent<void>>,
    onWbFieldUpdated: EventName<WbCanvasCustomEvent<{ id: number; patch: Partial<FieldMeta> }>>
};

export const WbCanvas: StencilReactComponent<WbCanvasElement, WbCanvasEvents, Components.WbCanvas> = /*@__PURE__*/ createComponent<WbCanvasElement, WbCanvasEvents, Components.WbCanvas>({
    tagName: 'wb-canvas',
    elementClass: WbCanvasElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onWbChange: 'wbChange',
        onWbFieldSelected: 'wbFieldSelected',
        onWbFieldDeselected: 'wbFieldDeselected',
        onWbFieldUpdated: 'wbFieldUpdated'
    } as WbCanvasEvents,
    defineCustomElement: defineWbCanvas
});

export type WbFormFieldEvents = NonNullable<unknown>;

export const WbFormField: StencilReactComponent<WbFormFieldElement, WbFormFieldEvents, Components.WbFormField, 'name' | 'label'> = /*@__PURE__*/ createComponent<WbFormFieldElement, WbFormFieldEvents, Components.WbFormField, 'name' | 'label'>({
    tagName: 'wb-form-field',
    elementClass: WbFormFieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as WbFormFieldEvents,
    defineCustomElement: defineWbFormField
});

export type WbFormRendererEvents = { onWbSubmit: EventName<WbFormRendererCustomEvent<Record<string, string>>> };

export const WbFormRenderer: StencilReactComponent<WbFormRendererElement, WbFormRendererEvents, Components.WbFormRenderer> = /*@__PURE__*/ createComponent<WbFormRendererElement, WbFormRendererEvents, Components.WbFormRenderer>({
    tagName: 'wb-form-renderer',
    elementClass: WbFormRendererElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWbSubmit: 'wbSubmit' } as WbFormRendererEvents,
    defineCustomElement: defineWbFormRenderer
});

export type WbInspectorEvents = { onWbFieldUpdated: EventName<WbInspectorCustomEvent<{ id: number; patch: Partial<FieldMeta> }>> };

export const WbInspector: StencilReactComponent<WbInspectorElement, WbInspectorEvents, Components.WbInspector> = /*@__PURE__*/ createComponent<WbInspectorElement, WbInspectorEvents, Components.WbInspector>({
    tagName: 'wb-inspector',
    elementClass: WbInspectorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWbFieldUpdated: 'wbFieldUpdated' } as WbInspectorEvents,
    defineCustomElement: defineWbInspector
});

export type WbPaletteEvents = {
    onWbAddField: EventName<WbPaletteCustomEvent<FieldTypeDef>>,
    onWbPaletteDragStart: EventName<WbPaletteCustomEvent<FieldTypeDef>>,
    onWbPaletteDragMove: EventName<WbPaletteCustomEvent<{ clientX: number; clientY: number }>>,
    onWbPaletteDragEnd: EventName<WbPaletteCustomEvent<FieldTypeDef | null>>
};

export const WbPalette: StencilReactComponent<WbPaletteElement, WbPaletteEvents, Components.WbPalette> = /*@__PURE__*/ createComponent<WbPaletteElement, WbPaletteEvents, Components.WbPalette>({
    tagName: 'wb-palette',
    elementClass: WbPaletteElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onWbAddField: 'wbAddField',
        onWbPaletteDragStart: 'wbPaletteDragStart',
        onWbPaletteDragMove: 'wbPaletteDragMove',
        onWbPaletteDragEnd: 'wbPaletteDragEnd'
    } as WbPaletteEvents,
    defineCustomElement: defineWbPalette
});
