/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FieldType } from "./components/wb-form-field/wb-form-field";
import { FieldType as FieldType1 } from "./components/wb-form-field/wb-form-field";
export { FieldType } from "./components/wb-form-field/wb-form-field";
export { FieldType as FieldType1 } from "./components/wb-form-field/wb-form-field";
export namespace Components {
    /**
     * Reorderable field list. Ported from the standalone touch-drag spike.
     * Key difference from that spike: rows are keyed by field id (`key={f.id}`
     * below), so Stencil's virtual-DOM diff reuses the same DOM node for a row
     * across re-renders instead of destroying/recreating it. That's what caused
     * the original bug (re-render killed the element mid-drag, silently ending
     * pointer capture) — keyed VDOM avoids it by construction, as long as the
     * key stays stable across the reorder.
     */
    interface WbCanvas {
        "addField": (type: FieldType, label: string) => Promise<void>;
    }
    /**
     * Renders ONE field from the JSON Schema / UI Schema pair and participates
     * natively in an ancestor <form> via ElementInternals — confirmed working
     * inside shadow DOM (including native validation-bubble anchoring) in the
     * standalone spike this replaces.
     * Multiple fields are namespaced by `name`, which should be the JSON
     * Pointer path from the schema (e.g. "personal.email"), not a bare label —
     * see the collision risk noted after the ElementInternals spike.
     */
    interface WbFormField {
        "label": string;
        /**
          * JSON Pointer path used as the form-submission key, e.g. "personal.email"
         */
        "name": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": FieldType1;
    }
    /**
     * Tap-to-add palette. This is the interaction validated in the mobile
     * FAB-and-sheet spike (tap a type, it's appended to the canvas) — it works
     * identically here whether triggered by a real FAB/sheet shell on mobile or
     * a plain click on desktop.
     * Desktop drag-from-palette straight onto the canvas (the cross-shadow-
     * boundary drag validated in the first spike) is intentionally not wired up
     * yet — worth adding once the tap-to-add path is confirmed against real
     * form-core schema output, since it's an enhancement layered on the same
     * wbAddField event rather than a different data path.
     */
    interface WbPalette {
    }
}
export interface WbCanvasCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWbCanvasElement;
}
export interface WbPaletteCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWbPaletteElement;
}
declare global {
    interface HTMLWbCanvasElementEventMap {
        "wbChange": FieldMeta[];
        "wbFieldSelected": FieldMeta;
    }
    /**
     * Reorderable field list. Ported from the standalone touch-drag spike.
     * Key difference from that spike: rows are keyed by field id (`key={f.id}`
     * below), so Stencil's virtual-DOM diff reuses the same DOM node for a row
     * across re-renders instead of destroying/recreating it. That's what caused
     * the original bug (re-render killed the element mid-drag, silently ending
     * pointer capture) — keyed VDOM avoids it by construction, as long as the
     * key stays stable across the reorder.
     */
    interface HTMLWbCanvasElement extends Components.WbCanvas, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWbCanvasElementEventMap>(type: K, listener: (this: HTMLWbCanvasElement, ev: WbCanvasCustomEvent<HTMLWbCanvasElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWbCanvasElementEventMap>(type: K, listener: (this: HTMLWbCanvasElement, ev: WbCanvasCustomEvent<HTMLWbCanvasElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWbCanvasElement: {
        prototype: HTMLWbCanvasElement;
        new (): HTMLWbCanvasElement;
    };
    /**
     * Renders ONE field from the JSON Schema / UI Schema pair and participates
     * natively in an ancestor <form> via ElementInternals — confirmed working
     * inside shadow DOM (including native validation-bubble anchoring) in the
     * standalone spike this replaces.
     * Multiple fields are namespaced by `name`, which should be the JSON
     * Pointer path from the schema (e.g. "personal.email"), not a bare label —
     * see the collision risk noted after the ElementInternals spike.
     */
    interface HTMLWbFormFieldElement extends Components.WbFormField, HTMLStencilElement {
    }
    var HTMLWbFormFieldElement: {
        prototype: HTMLWbFormFieldElement;
        new (): HTMLWbFormFieldElement;
    };
    interface HTMLWbPaletteElementEventMap {
        "wbAddField": FieldTypeDef;
    }
    /**
     * Tap-to-add palette. This is the interaction validated in the mobile
     * FAB-and-sheet spike (tap a type, it's appended to the canvas) — it works
     * identically here whether triggered by a real FAB/sheet shell on mobile or
     * a plain click on desktop.
     * Desktop drag-from-palette straight onto the canvas (the cross-shadow-
     * boundary drag validated in the first spike) is intentionally not wired up
     * yet — worth adding once the tap-to-add path is confirmed against real
     * form-core schema output, since it's an enhancement layered on the same
     * wbAddField event rather than a different data path.
     */
    interface HTMLWbPaletteElement extends Components.WbPalette, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWbPaletteElementEventMap>(type: K, listener: (this: HTMLWbPaletteElement, ev: WbPaletteCustomEvent<HTMLWbPaletteElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWbPaletteElementEventMap>(type: K, listener: (this: HTMLWbPaletteElement, ev: WbPaletteCustomEvent<HTMLWbPaletteElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWbPaletteElement: {
        prototype: HTMLWbPaletteElement;
        new (): HTMLWbPaletteElement;
    };
    interface HTMLElementTagNameMap {
        "wb-canvas": HTMLWbCanvasElement;
        "wb-form-field": HTMLWbFormFieldElement;
        "wb-palette": HTMLWbPaletteElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * Reorderable field list. Ported from the standalone touch-drag spike.
     * Key difference from that spike: rows are keyed by field id (`key={f.id}`
     * below), so Stencil's virtual-DOM diff reuses the same DOM node for a row
     * across re-renders instead of destroying/recreating it. That's what caused
     * the original bug (re-render killed the element mid-drag, silently ending
     * pointer capture) — keyed VDOM avoids it by construction, as long as the
     * key stays stable across the reorder.
     */
    interface WbCanvas {
        "onWbChange"?: (event: WbCanvasCustomEvent<FieldMeta[]>) => void;
        "onWbFieldSelected"?: (event: WbCanvasCustomEvent<FieldMeta>) => void;
    }
    /**
     * Renders ONE field from the JSON Schema / UI Schema pair and participates
     * natively in an ancestor <form> via ElementInternals — confirmed working
     * inside shadow DOM (including native validation-bubble anchoring) in the
     * standalone spike this replaces.
     * Multiple fields are namespaced by `name`, which should be the JSON
     * Pointer path from the schema (e.g. "personal.email"), not a bare label —
     * see the collision risk noted after the ElementInternals spike.
     */
    interface WbFormField {
        /**
          * If `true`, the user cannot interact with the element.
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        "label": string;
        /**
          * JSON Pointer path used as the form-submission key, e.g. "personal.email"
         */
        "name": string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: FieldType1;
    }
    /**
     * Tap-to-add palette. This is the interaction validated in the mobile
     * FAB-and-sheet spike (tap a type, it's appended to the canvas) — it works
     * identically here whether triggered by a real FAB/sheet shell on mobile or
     * a plain click on desktop.
     * Desktop drag-from-palette straight onto the canvas (the cross-shadow-
     * boundary drag validated in the first spike) is intentionally not wired up
     * yet — worth adding once the tap-to-add path is confirmed against real
     * form-core schema output, since it's an enhancement layered on the same
     * wbAddField event rather than a different data path.
     */
    interface WbPalette {
        "onWbAddField"?: (event: WbPaletteCustomEvent<FieldTypeDef>) => void;
    }

    interface WbFormFieldAttributes {
        "name": string;
        "type": FieldType;
        "label": string;
        "required": boolean;
    }

    interface IntrinsicElements {
        "wb-canvas": WbCanvas;
        "wb-form-field": Omit<WbFormField, keyof WbFormFieldAttributes> & { [K in keyof WbFormField & keyof WbFormFieldAttributes]?: WbFormField[K] } & { [K in keyof WbFormField & keyof WbFormFieldAttributes as `attr:${K}`]?: WbFormFieldAttributes[K] } & { [K in keyof WbFormField & keyof WbFormFieldAttributes as `prop:${K}`]?: WbFormField[K] } & OneOf<"name", WbFormField["name"], WbFormFieldAttributes["name"]> & OneOf<"label", WbFormField["label"], WbFormFieldAttributes["label"]>;
        "wb-palette": WbPalette;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Reorderable field list. Ported from the standalone touch-drag spike.
             * Key difference from that spike: rows are keyed by field id (`key={f.id}`
             * below), so Stencil's virtual-DOM diff reuses the same DOM node for a row
             * across re-renders instead of destroying/recreating it. That's what caused
             * the original bug (re-render killed the element mid-drag, silently ending
             * pointer capture) — keyed VDOM avoids it by construction, as long as the
             * key stays stable across the reorder.
             */
            "wb-canvas": LocalJSX.IntrinsicElements["wb-canvas"] & JSXBase.HTMLAttributes<HTMLWbCanvasElement>;
            /**
             * Renders ONE field from the JSON Schema / UI Schema pair and participates
             * natively in an ancestor <form> via ElementInternals — confirmed working
             * inside shadow DOM (including native validation-bubble anchoring) in the
             * standalone spike this replaces.
             * Multiple fields are namespaced by `name`, which should be the JSON
             * Pointer path from the schema (e.g. "personal.email"), not a bare label —
             * see the collision risk noted after the ElementInternals spike.
             */
            "wb-form-field": LocalJSX.IntrinsicElements["wb-form-field"] & JSXBase.HTMLAttributes<HTMLWbFormFieldElement>;
            /**
             * Tap-to-add palette. This is the interaction validated in the mobile
             * FAB-and-sheet spike (tap a type, it's appended to the canvas) — it works
             * identically here whether triggered by a real FAB/sheet shell on mobile or
             * a plain click on desktop.
             * Desktop drag-from-palette straight onto the canvas (the cross-shadow-
             * boundary drag validated in the first spike) is intentionally not wired up
             * yet — worth adding once the tap-to-add path is confirmed against real
             * form-core schema output, since it's an enhancement layered on the same
             * wbAddField event rather than a different data path.
             */
            "wb-palette": LocalJSX.IntrinsicElements["wb-palette"] & JSXBase.HTMLAttributes<HTMLWbPaletteElement>;
        }
    }
}
