/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FieldMeta, FieldSubtype, FieldType, Restrictions } from "./core";
import { FieldTypeDef } from "./components/wb-palette/wb-palette";
export { FieldMeta, FieldSubtype, FieldType, Restrictions } from "./core";
export { FieldTypeDef } from "./components/wb-palette/wb-palette";
export namespace Components {
    /**
     * Reorderable field list. Ported from the standalone touch-drag spike.
     * Key difference from that spike: rows are keyed by field id (`key={f.id}`
     * below), so Stencil's virtual-DOM diff reuses the same DOM node for a row
     * across re-renders instead of destroying/recreating it. That's what caused
     * the original bug (re-render killed the element mid-drag, silently ending
     * pointer capture) — keyed VDOM avoids it by construction, as long as the
     * key stays stable across the reorder.
     */
    interface WbCanvas {
        "addField": (type: FieldMeta["type"], label: string, subtype?: FieldSubtype, design?: { kind: "design"; designType: FieldMeta["designType"]; }) => Promise<void>;
        "addFieldAfter": (type: FieldMeta["type"], label: string, subtype?: FieldSubtype, design?: { kind: "design"; designType: FieldMeta["designType"]; }) => Promise<void>;
        "beginExternalDrag": () => Promise<void>;
        "cancelExternalDrag": () => Promise<void>;
        "commitExternalInsert": (type: FieldMeta["type"], label: string, subtype?: FieldSubtype, design?: { kind: "design"; designType: FieldMeta["designType"]; }) => Promise<void>;
        "importState": (fields: FieldMeta[]) => Promise<void>;
        "selectField": (id: number | null) => Promise<void>;
        "setExternalHoverIndex": (x: number, y: number) => Promise<void>;
        "updateField": (id: number, patch: Partial<FieldMeta>) => Promise<void>;
    }
    /**
     * Renders ONE field from the JSON Schema / UI Schema pair and participates
     * natively in an ancestor <form> via ElementInternals — confirmed working
     * inside shadow DOM (including native validation-bubble anchoring) in the
     * standalone spike this replaces.
     * Multiple fields are namespaced by `name`, which should be the JSON
     * Pointer path from the schema (e.g. "personal.email"), not a bare label —
     * see the collision risk noted after the ElementInternals spike.
     */
    interface WbFormField {
        /**
          * When true, the control is rendered inert (not focusable/editable) but keeps its normal enabled appearance.
          * @default false
         */
        "disabled": boolean;
        "initialLines"?: number;
        "label": string;
        "maxHeight"?: number;
        /**
          * @default false
         */
        "multiline": boolean;
        /**
          * JSON Pointer path used as the form-submission key, e.g. "personal.email"
         */
        "name": string;
        /**
          * Ordered list of selectable choices rendered as `<option>` children for `type="select"`.
         */
        "options"?: { key: string; label: string }[];
        /**
          * Muted helper text shown while a richtext editor is empty (richtext only).
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required": boolean;
        "restrictions"?: Restrictions;
        "subtype"?: FieldSubtype;
        /**
          * @default 'text'
         */
        "type": FieldType;
    }
    interface WbFormRenderer {
        /**
          * @default []
         */
        "fields": FieldMeta[];
        "setFields": (fields: FieldMeta[]) => Promise<void>;
    }
    interface WbInspector {
        /**
          * @default null
         */
        "field": FieldMeta | null;
        "setField": (field: FieldMeta | null) => Promise<void>;
    }
    interface WbPalette {
    }
}
export interface WbCanvasCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWbCanvasElement;
}
export interface WbFormRendererCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWbFormRendererElement;
}
export interface WbInspectorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWbInspectorElement;
}
export interface WbPaletteCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWbPaletteElement;
}
declare global {
    interface HTMLWbCanvasElementEventMap {
        "wbChange": FieldMeta[];
        "wbFieldSelected": FieldMeta;
        "wbFieldDeselected": void;
        "wbFieldUpdated": { id: number; patch: Partial<FieldMeta> };
    }
    /**
     * Reorderable field list. Ported from the standalone touch-drag spike.
     * Key difference from that spike: rows are keyed by field id (`key={f.id}`
     * below), so Stencil's virtual-DOM diff reuses the same DOM node for a row
     * across re-renders instead of destroying/recreating it. That's what caused
     * the original bug (re-render killed the element mid-drag, silently ending
     * pointer capture) — keyed VDOM avoids it by construction, as long as the
     * key stays stable across the reorder.
     */
    interface HTMLWbCanvasElement extends Components.WbCanvas, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWbCanvasElementEventMap>(type: K, listener: (this: HTMLWbCanvasElement, ev: WbCanvasCustomEvent<HTMLWbCanvasElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWbCanvasElementEventMap>(type: K, listener: (this: HTMLWbCanvasElement, ev: WbCanvasCustomEvent<HTMLWbCanvasElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWbCanvasElement: {
        prototype: HTMLWbCanvasElement;
        new (): HTMLWbCanvasElement;
    };
    /**
     * Renders ONE field from the JSON Schema / UI Schema pair and participates
     * natively in an ancestor <form> via ElementInternals — confirmed working
     * inside shadow DOM (including native validation-bubble anchoring) in the
     * standalone spike this replaces.
     * Multiple fields are namespaced by `name`, which should be the JSON
     * Pointer path from the schema (e.g. "personal.email"), not a bare label —
     * see the collision risk noted after the ElementInternals spike.
     */
    interface HTMLWbFormFieldElement extends Components.WbFormField, HTMLStencilElement {
    }
    var HTMLWbFormFieldElement: {
        prototype: HTMLWbFormFieldElement;
        new (): HTMLWbFormFieldElement;
    };
    interface HTMLWbFormRendererElementEventMap {
        "wbSubmit": Record<string, string>;
    }
    interface HTMLWbFormRendererElement extends Components.WbFormRenderer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWbFormRendererElementEventMap>(type: K, listener: (this: HTMLWbFormRendererElement, ev: WbFormRendererCustomEvent<HTMLWbFormRendererElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWbFormRendererElementEventMap>(type: K, listener: (this: HTMLWbFormRendererElement, ev: WbFormRendererCustomEvent<HTMLWbFormRendererElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWbFormRendererElement: {
        prototype: HTMLWbFormRendererElement;
        new (): HTMLWbFormRendererElement;
    };
    interface HTMLWbInspectorElementEventMap {
        "wbFieldUpdated": { id: number; patch: Partial<FieldMeta> };
    }
    interface HTMLWbInspectorElement extends Components.WbInspector, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWbInspectorElementEventMap>(type: K, listener: (this: HTMLWbInspectorElement, ev: WbInspectorCustomEvent<HTMLWbInspectorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWbInspectorElementEventMap>(type: K, listener: (this: HTMLWbInspectorElement, ev: WbInspectorCustomEvent<HTMLWbInspectorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWbInspectorElement: {
        prototype: HTMLWbInspectorElement;
        new (): HTMLWbInspectorElement;
    };
    interface HTMLWbPaletteElementEventMap {
        "wbAddField": FieldTypeDef;
        "wbPaletteDragStart": FieldTypeDef;
        "wbPaletteDragMove": { clientX: number; clientY: number };
        "wbPaletteDragEnd": FieldTypeDef | null;
    }
    interface HTMLWbPaletteElement extends Components.WbPalette, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWbPaletteElementEventMap>(type: K, listener: (this: HTMLWbPaletteElement, ev: WbPaletteCustomEvent<HTMLWbPaletteElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWbPaletteElementEventMap>(type: K, listener: (this: HTMLWbPaletteElement, ev: WbPaletteCustomEvent<HTMLWbPaletteElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWbPaletteElement: {
        prototype: HTMLWbPaletteElement;
        new (): HTMLWbPaletteElement;
    };
    interface HTMLElementTagNameMap {
        "wb-canvas": HTMLWbCanvasElement;
        "wb-form-field": HTMLWbFormFieldElement;
        "wb-form-renderer": HTMLWbFormRendererElement;
        "wb-inspector": HTMLWbInspectorElement;
        "wb-palette": HTMLWbPaletteElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * Reorderable field list. Ported from the standalone touch-drag spike.
     * Key difference from that spike: rows are keyed by field id (`key={f.id}`
     * below), so Stencil's virtual-DOM diff reuses the same DOM node for a row
     * across re-renders instead of destroying/recreating it. That's what caused
     * the original bug (re-render killed the element mid-drag, silently ending
     * pointer capture) — keyed VDOM avoids it by construction, as long as the
     * key stays stable across the reorder.
     */
    interface WbCanvas {
        "onWbChange"?: (event: WbCanvasCustomEvent<FieldMeta[]>) => void;
        "onWbFieldDeselected"?: (event: WbCanvasCustomEvent<void>) => void;
        "onWbFieldSelected"?: (event: WbCanvasCustomEvent<FieldMeta>) => void;
        "onWbFieldUpdated"?: (event: WbCanvasCustomEvent<{ id: number; patch: Partial<FieldMeta> }>) => void;
    }
    /**
     * Renders ONE field from the JSON Schema / UI Schema pair and participates
     * natively in an ancestor <form> via ElementInternals — confirmed working
     * inside shadow DOM (including native validation-bubble anchoring) in the
     * standalone spike this replaces.
     * Multiple fields are namespaced by `name`, which should be the JSON
     * Pointer path from the schema (e.g. "personal.email"), not a bare label —
     * see the collision risk noted after the ElementInternals spike.
     */
    interface WbFormField {
        /**
          * When true, the control is rendered inert (not focusable/editable) but keeps its normal enabled appearance.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        "initialLines"?: number;
        "label": string;
        "maxHeight"?: number;
        /**
          * @default false
         */
        "multiline"?: boolean;
        /**
          * JSON Pointer path used as the form-submission key, e.g. "personal.email"
         */
        "name": string;
        /**
          * Ordered list of selectable choices rendered as `<option>` children for `type="select"`.
         */
        "options"?: { key: string; label: string }[];
        /**
          * Muted helper text shown while a richtext editor is empty (richtext only).
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        "restrictions"?: Restrictions;
        "subtype"?: FieldSubtype;
        /**
          * @default 'text'
         */
        "type"?: FieldType;
    }
    interface WbFormRenderer {
        /**
          * @default []
         */
        "fields"?: FieldMeta[];
        "onWbSubmit"?: (event: WbFormRendererCustomEvent<Record<string, string>>) => void;
    }
    interface WbInspector {
        /**
          * @default null
         */
        "field"?: FieldMeta | null;
        "onWbFieldUpdated"?: (event: WbInspectorCustomEvent<{ id: number; patch: Partial<FieldMeta> }>) => void;
    }
    interface WbPalette {
        "onWbAddField"?: (event: WbPaletteCustomEvent<FieldTypeDef>) => void;
        "onWbPaletteDragEnd"?: (event: WbPaletteCustomEvent<FieldTypeDef | null>) => void;
        "onWbPaletteDragMove"?: (event: WbPaletteCustomEvent<{ clientX: number; clientY: number }>) => void;
        "onWbPaletteDragStart"?: (event: WbPaletteCustomEvent<FieldTypeDef>) => void;
    }

    interface WbFormFieldAttributes {
        "name": string;
        "type": FieldType;
        "label": string;
        "required": boolean;
        "subtype": FieldSubtype;
        "multiline": boolean;
        "initialLines": number;
        "maxHeight": number;
        "placeholder": string;
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "wb-canvas": WbCanvas;
        "wb-form-field": Omit<WbFormField, keyof WbFormFieldAttributes> & { [K in keyof WbFormField & keyof WbFormFieldAttributes]?: WbFormField[K] } & { [K in keyof WbFormField & keyof WbFormFieldAttributes as `attr:${K}`]?: WbFormFieldAttributes[K] } & { [K in keyof WbFormField & keyof WbFormFieldAttributes as `prop:${K}`]?: WbFormField[K] } & OneOf<"name", WbFormField["name"], WbFormFieldAttributes["name"]> & OneOf<"label", WbFormField["label"], WbFormFieldAttributes["label"]>;
        "wb-form-renderer": WbFormRenderer;
        "wb-inspector": WbInspector;
        "wb-palette": WbPalette;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Reorderable field list. Ported from the standalone touch-drag spike.
             * Key difference from that spike: rows are keyed by field id (`key={f.id}`
             * below), so Stencil's virtual-DOM diff reuses the same DOM node for a row
             * across re-renders instead of destroying/recreating it. That's what caused
             * the original bug (re-render killed the element mid-drag, silently ending
             * pointer capture) — keyed VDOM avoids it by construction, as long as the
             * key stays stable across the reorder.
             */
            "wb-canvas": LocalJSX.IntrinsicElements["wb-canvas"] & JSXBase.HTMLAttributes<HTMLWbCanvasElement>;
            /**
             * Renders ONE field from the JSON Schema / UI Schema pair and participates
             * natively in an ancestor <form> via ElementInternals — confirmed working
             * inside shadow DOM (including native validation-bubble anchoring) in the
             * standalone spike this replaces.
             * Multiple fields are namespaced by `name`, which should be the JSON
             * Pointer path from the schema (e.g. "personal.email"), not a bare label —
             * see the collision risk noted after the ElementInternals spike.
             */
            "wb-form-field": LocalJSX.IntrinsicElements["wb-form-field"] & JSXBase.HTMLAttributes<HTMLWbFormFieldElement>;
            "wb-form-renderer": LocalJSX.IntrinsicElements["wb-form-renderer"] & JSXBase.HTMLAttributes<HTMLWbFormRendererElement>;
            "wb-inspector": LocalJSX.IntrinsicElements["wb-inspector"] & JSXBase.HTMLAttributes<HTMLWbInspectorElement>;
            "wb-palette": LocalJSX.IntrinsicElements["wb-palette"] & JSXBase.HTMLAttributes<HTMLWbPaletteElement>;
        }
    }
}
